// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nuciqjpwltieyrdzvagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51Y2lxanB3bHRpZXlyZHp2YWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2Nzg5NjcsImV4cCI6MjA4NDI1NDk2N30.vRrdQrnaQ1ZgAeLKsoDo9JfqAIEr4-e3-Mdho3U-sJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);